spring:
  application:
    name: ev-us-information-manager
  cloud:
    discovery:
      enabled: true

server:
  port: 8085

logging:
  level:
    root: debug

management:
  endpoints:
    web:
      exposure:
        include: info, routes, health

ev:
  common-urls:
    gateway-url: http://localhost:9091
    user-service-url: /userProfile
    payment-service-url: /payments
    information-manager-url: /informationManager
    business-service-url: /businessService

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:9090/eureka