version: "3"

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres:13
    container_name: postgres_keycloak
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  keycloak:
    build: .
    container_name: keycloak_evolve
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - 9990:8080
    volumes:
      - ./keycloak/themes/evolve:/opt/jboss/keycloak/themes/evolve
    depends_on:
      - postgres
